### ISSUE TITLE
Wrong listen configuration / No connection with IPv6

### ISSUE THREAD

**Issue by Stoney49th** [OpenMediaVault-Plugin-Developers/openmediavault-website#3]
The default config sting is "listen PORT;", where it should be "listen [::]:PORT ipv6only=off;" if there is any IPv6 connectivity on the system. This also applies to the SSL port where the "[::]:" is missing.

As a result, the website is not reachable via IPv6 which bad, considering the increasing use of IPv6.

**Comment by ryecoaaron** [comment]
I think this issue belong with the openmediavault-nginx package.  This plugin was 0.5 only and works with apache.  Can you please create a new issue on that package?

**Comment by Stoney49th** [comment]
sure, will do so ASAP...sorry for the wrong plugin/repo :)
